version: '2'
services:
  workshop_postgres:
    image: postgres:12
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  workshop_zookeeper:
    image: confluentinc/cp-zookeeper:5.2.3
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"
  workshop_kafka:
    image: confluentinc/cp-kafka:5.2.3
    ports:
      - 29092:29092
    depends_on:
      - workshop_zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: workshop_zookeeper:32181
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:29092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://workshop_kafka:9092,EXTERNAL://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"
  workshop_kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9001:9000
    depends_on:
      - workshop_kafka
    environment:
      KAFKA_BROKERCONNECT: workshop_kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"